const mongoose = require("mongoose");

const restaurantSchema = new mongoose.Schema(
  {
    owner: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    name: { type: String, required: true, trim: true },
    description: String,
    phone: String,
    supportContact: String,
    address: String,
    localArea: String,
    location: { lat: Number, lng: Number },
    image: String,
    logo: String,
    banner: String,
    cuisineTypes: [String],
    ownerCnic: String,
    businessProof: String,
    taxRegistration: String,
    bankAccountType: { type: String, enum: ["JazzCash", "EasyPaisa", "HBL Konnect", "Bank", ""], default: "" },
    payoutAccountTitle: String,
    bankAccountNumber: String,
    deliveryRadiusKm: { type: Number, default: 5 },
    ownerPhone: String,
    ownerEmail: String,
    licenseImage: String,
    cnicFrontImage: String,
    cnicBackImage: String,
    kitchenImage: String,
    verificationNotes: String,
    documentStatus: { type: String, enum: ["missing", "submitted", "verified", "rejected"], default: "missing" },
    deliveryPreference: { type: String, enum: ["platform_riders", "self_delivery", "hybrid"], default: "platform_riders" },
    businessHours: {
      opensAt: { type: String, default: "11:00" },
      closesAt: { type: String, default: "23:30" },
    },
    isFeatured: { type: Boolean, default: false },
    offerText: String,
    deliveryFeeBase: { type: Number, default: 90 },
    isOpen: { type: Boolean, default: true },
    approvalStatus: { type: String, enum: ["pending", "pending_review", "approved", "rejected", "suspended"], default: "pending_review" },
    isActive: { type: Boolean, default: true },
    qualityFlag: { type: Boolean, default: false },
    qualityFlagReason: String,
    kitchenLoad: { type: String, enum: ["low", "medium", "high"], default: "low" },
    averagePreparationTime: { type: Number, default: 20 },
    accuracyRate: { type: Number, default: 100 },
    trustScore: { type: Number, default: 100, min: 0, max: 100 },
    rating: { type: Number, default: 0 },
    totalReviews: { type: Number, default: 0 },
    totalSales: { type: Number, default: 0 },
    totalRevenue: { type: Number, default: 0 },
    pendingSettlement: { type: Number, default: 0 },
    completedSales: { type: Number, default: 0 },
    platformCommission: { type: Number, default: 0 },
    cancelledOrders: { type: Number, default: 0 },
    commissionRate: { type: Number, default: 15 },
    completedOrders: { type: Number, default: 0 },
    rejectedOrders: { type: Number, default: 0 },
    supportTicketCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Restaurant", restaurantSchema);
