const mongoose = require("mongoose");

const riderSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, unique: true },
    vehicleType: { type: String, enum: ["bike", "car", "cycle"], default: "bike" },
    cnic: { type: String, trim: true },
    bikeNumber: { type: String, trim: true },
    vehicleNumber: { type: String, trim: true },
    drivingLicence: { type: String, trim: true },
    drivingLicense: { type: String, trim: true },
    emergencyContact: { type: String, trim: true },
    preferredArea: { type: String, trim: true },
    ageConfirmed: { type: Boolean, default: false },
    paymentAccountType: { type: String, enum: ["JazzCash", "EasyPaisa", "HBL Konnect", "NayaPay", "SadaPay", "Bank", ""], default: "" },
    accountTitle: { type: String, trim: true },
    paymentAccountNumber: { type: String, trim: true },
    iban: { type: String, trim: true },
    paymentAccount: {
      type: { type: String },
      title: String,
      number: String,
      iban: String,
    },
    profileImage: String,
    phoneVerified: { type: Boolean, default: false },
    currentLocation: { lat: Number, lng: Number },
    isOnline: { type: Boolean, default: false },
    availabilityStatus: { type: String, enum: ["pending_approval", "approved_offline", "online", "busy", "suspended"], default: "pending_approval" },
    approvalStatus: { type: String, enum: ["pending", "approved", "rejected", "suspended"], default: "pending" },
    isActive: { type: Boolean, default: true },
    isSuspended: { type: Boolean, default: false },
    suspensionReason: String,
    activeOrder: { type: mongoose.Schema.Types.ObjectId, ref: "Order" },
    activeOrders: [{ type: mongoose.Schema.Types.ObjectId, ref: "Order" }],
    earnings: { type: Number, default: 0 },
    dailyEarnings: { type: Number, default: 0 },
    weeklyEarnings: { type: Number, default: 0 },
    walletBalance: { type: Number, default: 0 },
    pendingPayout: { type: Number, default: 0 },
    totalLifetimeEarnings: { type: Number, default: 0 },
    codCollectedToday: { type: Number, default: 0 },
    maxBatchOrders: { type: Number, default: 3 },
    workloadScore: { type: Number, default: 0 },
    trustScore: { type: Number, default: 100, min: 0, max: 100 },
    acceptanceRate: { type: Number, default: 100, min: 0, max: 100 },
    cancellationRate: { type: Number, default: 0, min: 0, max: 100 },
    averageDeliveryTime: { type: Number, default: 0 },
    rejectedOrders: [{ type: mongoose.Schema.Types.ObjectId, ref: "Order" }],
    completedDeliveries: { type: Number, default: 0 },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Rider", riderSchema);
